// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { getNotifications, getUsers, getUsersById, type Options, patchNotificationsByIdRead, postUsers } from '../sdk.gen';
import type { GetNotificationsData, GetNotificationsResponse, GetUsersByIdData, GetUsersByIdResponse, GetUsersData, GetUsersResponse, PatchNotificationsByIdReadData, PatchNotificationsByIdReadResponse, PostUsersData, PostUsersResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options);

/**
 * Get all users
 */
export const getUsersOptions = (options?: Options<GetUsersData>) => queryOptions<GetUsersResponse, AxiosError<DefaultError>, GetUsersResponse, ReturnType<typeof getUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersQueryKey(options)
});

/**
 * Create user
 */
export const postUsersMutation = (options?: Partial<Options<PostUsersData>>): UseMutationOptions<PostUsersResponse, AxiosError<DefaultError>, Options<PostUsersData>> => {
    const mutationOptions: UseMutationOptions<PostUsersResponse, AxiosError<DefaultError>, Options<PostUsersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postUsers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUsersByIdQueryKey = (options: Options<GetUsersByIdData>) => createQueryKey('getUsersById', options);

/**
 * Get user by ID
 */
export const getUsersByIdOptions = (options: Options<GetUsersByIdData>) => queryOptions<GetUsersByIdResponse, AxiosError<DefaultError>, GetUsersByIdResponse, ReturnType<typeof getUsersByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsersById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersByIdQueryKey(options)
});

export const getNotificationsQueryKey = (options?: Options<GetNotificationsData>) => createQueryKey('getNotifications', options);

/**
 * Get all notifications
 */
export const getNotificationsOptions = (options?: Options<GetNotificationsData>) => queryOptions<GetNotificationsResponse, AxiosError<DefaultError>, GetNotificationsResponse, ReturnType<typeof getNotificationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNotifications({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNotificationsQueryKey(options)
});

/**
 * Mark notification as read
 */
export const patchNotificationsByIdReadMutation = (options?: Partial<Options<PatchNotificationsByIdReadData>>): UseMutationOptions<PatchNotificationsByIdReadResponse, AxiosError<DefaultError>, Options<PatchNotificationsByIdReadData>> => {
    const mutationOptions: UseMutationOptions<PatchNotificationsByIdReadResponse, AxiosError<DefaultError>, Options<PatchNotificationsByIdReadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchNotificationsByIdRead({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
