// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetNotificationsData, GetNotificationsResponses, GetUsersByIdData, GetUsersByIdResponses, GetUsersData, GetUsersResponses, PatchNotificationsByIdReadData, PatchNotificationsByIdReadResponses, PostUsersData, PostUsersResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all users
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/users',
    ...options
});

/**
 * Create user
 */
export const postUsers = <ThrowOnError extends boolean = false>(options: Options<PostUsersData, ThrowOnError>) => (options.client ?? client).post<PostUsersResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get user by ID
 */
export const getUsersById = <ThrowOnError extends boolean = false>(options: Options<GetUsersByIdData, ThrowOnError>) => (options.client ?? client).get<GetUsersByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/users/{id}',
    ...options
});

/**
 * Get all notifications
 */
export const getNotifications = <ThrowOnError extends boolean = false>(options?: Options<GetNotificationsData, ThrowOnError>) => (options?.client ?? client).get<GetNotificationsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/notifications',
    ...options
});

/**
 * Mark notification as read
 */
export const patchNotificationsByIdRead = <ThrowOnError extends boolean = false>(options: Options<PatchNotificationsByIdReadData, ThrowOnError>) => (options.client ?? client).patch<PatchNotificationsByIdReadResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/notifications/{id}/read',
    ...options
});
