// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3000/api' | (string & {});
};

export type UsersSwaggerUser = {
    id: number;
    name: string;
    email: string;
    createdAt?: string;
};

export type UsersSwaggerUserList = Array<UsersSwaggerUser>;

export type UsersSwaggerCreateUserDto = {
    name: string;
    email: string;
};

export type NotificationsSwaggerNotification = {
    id: number;
    title: string;
    message?: string;
    read: boolean;
    createdAt?: string;
};

export type NotificationsSwaggerNotificationList = Array<NotificationsSwaggerNotification>;

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * List of users
     */
    200: UsersSwaggerUserList;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body: UsersSwaggerCreateUserDto;
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersResponses = {
    /**
     * Created
     */
    201: UsersSwaggerUser;
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdResponses = {
    /**
     * User found
     */
    200: UsersSwaggerUser;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type GetNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications';
};

export type GetNotificationsResponses = {
    /**
     * Notification list
     */
    200: NotificationsSwaggerNotificationList;
};

export type GetNotificationsResponse = GetNotificationsResponses[keyof GetNotificationsResponses];

export type PatchNotificationsByIdReadData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type PatchNotificationsByIdReadResponses = {
    /**
     * Updated
     */
    200: NotificationsSwaggerNotification;
};

export type PatchNotificationsByIdReadResponse = PatchNotificationsByIdReadResponses[keyof PatchNotificationsByIdReadResponses];
