// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zUsersSwaggerUser = z.object({
    id: z.int(),
    name: z.string(),
    email: z.email(),
    createdAt: z.optional(z.iso.datetime())
});

export const zUsersSwaggerUserList = z.array(zUsersSwaggerUser);

export const zUsersSwaggerCreateUserDto = z.object({
    name: z.string(),
    email: z.email()
});

export const zNotificationsSwaggerNotification = z.object({
    id: z.int(),
    title: z.string(),
    message: z.optional(z.string()),
    read: z.boolean(),
    createdAt: z.optional(z.iso.datetime())
});

export const zNotificationsSwaggerNotificationList = z.array(zNotificationsSwaggerNotification);

export const zGetUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * List of users
 */
export const zGetUsersResponse = zUsersSwaggerUserList;

export const zPostUsersData = z.object({
    body: zUsersSwaggerCreateUserDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostUsersResponse = zUsersSwaggerUser;

export const zGetUsersByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * User found
 */
export const zGetUsersByIdResponse = zUsersSwaggerUser;

export const zGetNotificationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Notification list
 */
export const zGetNotificationsResponse = zNotificationsSwaggerNotificationList;

export const zPatchNotificationsByIdReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Updated
 */
export const zPatchNotificationsByIdReadResponse = zNotificationsSwaggerNotification;
